project_veristock/project_veristock/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stock.urls')),
    path('', include('user.urls')),
]

project_veristock/stock/urls.py
from django.urls import path
from stock.views import *
from . import views

urlpatterns = [
    # Urls Product
    path('producto/index/', ProductListView.as_view(), name='producto_index'),
    path('producto/crear/', ProductCreateView.as_view(), name='crear_producto'),
    path('producto/eliminar/<int:pk>', ProductDeleteView.as_view(), name='eliminar_producto'),
    path('producto/editar/<int:pk>', ProductUpdateView.as_view(), name='editar_producto'),

    # Urls Entries
    
    path('producto/agregar_stock/<int:id>', views.addStockProduct, name='agregar_stock'),

    # Urls Sale

    path('venta/index/', SaleListView.as_view(), name='venta_index'),
    path('venta/crear/', SaleCreateView.as_view(), name='crear_venta'),
    path('venta/eliminar/<int:pk>', SaleDeleteView.as_view(), name='eliminar_venta'),
    path('venta/editar/<int:pk>', SaleUpdateView.as_view(), name='editar_venta'),
    
    # Urls Devolution
    path('devolucion/index/', DevolutionListView.as_view(), name='devolucion_index'),
    path('devolucion/crear/', DevolutionCreateView.as_view(), name='crear_devolucion'),
    path('devolucion/eliminar/<int:pk>', DevolutionDeleteView.as_view(), name='eliminar_devolucion'),
    path('devolucion/editar/<int:pk>', DevolutionUpdateView.as_view(), name='editar_devolucion'),

    # Pdf's
    path('venta/pdf/<int:pk>', SaleInvoicePdfView.as_view(), name='pdf_venta'),
]

project_veristock/user/urls.py
from django.urls import path
from user.views import *
from . import views
from django.contrib.auth.views import *

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('home', views.home, name='home'),
    path('base/', views.base, name='base'),
    path('iniciar_sesion/', LoginFormView.as_view(), name='iniciar_sesion'),
    path('logout/', LogoutView.as_view(), name='cerrar_sesion'),
    path('registrar/', views.register, name='registrar'),

    # Urls User
    path('usuario/index/', UserListView.as_view(), name='usuario_index'),
    path('usuario/crear/', UserCreateView.as_view(), name='crear_usuario'),
    path('usuario/eliminar/<int:pk>', UserDeleteView.as_view(), name='eliminar_usuario'),
    path('usuario/editar/<int:pk>', UserUpdateView.as_view(), name='editar_usuario'),

    # Urls Customer
    path('cliente/index/', CustomerListView.as_view(), name='cliente_index'),
    path('cliente/crear/', CustomerCreateView.as_view(), name='crear_cliente'),
    path('cliente/eliminar/<int:pk>', CustomerDeleteView.as_view(), name='eliminar_cliente'),
    path('cliente/editar/<int:pk>', CustomerUpdateView.as_view(), name='editar_cliente'),
]

project_veristock/stock/models.py
from django.db import models
from django.forms import model_to_dict
from user.models import Customer, User
from .choices import estado, garantia, motivo

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, verbose_name='Nombre')
    cost_sale = models.IntegerField(verbose_name='Costo Venta', default=0, null=False)
    brand = models.CharField(max_length=100, verbose_name='Marca')
    reference = models.CharField(max_length=100, verbose_name='Referencia')
    warranty = models.CharField(max_length=10, choices=garantia, verbose_name='Garantia')
    time_warranty = models.IntegerField(verbose_name='Tiempo Garantia')
    stock = models.IntegerField(verbose_name='Stock', default=0, null=False)

    def __str__(self):
        return '{} {} {}'.format(self.name, self.brand, self.reference)

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        ordering = ['id']
        verbose_name = 'Producto'
        unique_together = ('name','brand','reference')

class Entries(models.Model):
    id = models.AutoField(primary_key=True)
    id_product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Producto')
    date = models.DateField(verbose_name="Fecha de entrada de productos.")
    quantity = models.IntegerField(verbose_name="Cantidad")
    price = models.IntegerField(verbose_name="Precio")

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ['-date']
        verbose_name = 'Entrada'

class Devolution(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateField(verbose_name='Fecha')
    reason = models.CharField(max_length=100, verbose_name='Motivo', choices=motivo)
    remarks = models.TextField(null=True, verbose_name='Observaciones')
    id_product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Producto en devolución')

    def __str__(self):
        return self.reason

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        ordering = ['reason']
        verbose_name = 'Devolution'

class Sale(models.Model):
    invoice_number = models.AutoField(verbose_name='Numero Factura', primary_key=True)
    date = models.DateField(verbose_name='Fecha')
    totalSale = models.IntegerField(verbose_name='Total Venta')
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name='Cliente')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Usuario')

    def __str__(self):
        return str(self.invoice_number)

    def toJSON(self):
        item = model_to_dict(self)
        item['totalSale'] = int(self.totalSale)
        item['customer'] = self.customer.toJSON()
        item['user'] = self.user.toJSON()
        return item

    class Meta:
        ordering = ['invoice_number']
        verbose_name = 'Venta'

class Details_sale(models.Model):
    id = models.AutoField(primary_key=True)
    invoice_number = models.ForeignKey(Sale, on_delete=models.CASCADE)
    id_product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    totalPrice = models.IntegerField()

    def __str__(self):
        return str(self.invoice_number)

    def toJSON(self):
        item = model_to_dict(self)
        item['id_product'] = self.id_product.toJSON()
        return item

    class Meta:
        verbose_name = 'Detalle de Venta'
        ordering = ['invoice_number']

project_veristock/stock/views.py
import datetime
import json
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect
from django.db.models import Q
from django.db import transaction
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from project_veristock.settings import STATIC_URL

from user.models import Customer, User
from .models import Product, Sale, Devolution, Entries, Details_sale
from .forms import ProductForm, SaleForm, DevolutionForm

import os
from django.conf import settings
from django.template.loader import get_template
from xhtml2pdf import pisa

# CRUD Product

class ProductListView(ListView, LoginRequiredMixin, PermissionRequiredMixin):
    permission_required = ''
    model = Product
    template_name = 'stock/producto/index.html'
    
    @method_decorator(login_required)
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titlePaginador'] = 'Lista de Productos'
        context['botonCrear'] = 'Crear nuevo producto'
        context['urlCrear'] = reverse_lazy('crear_producto')
        context['entries'] = Entries.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchData':
                data = []
                for i in Product.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error.'
        except Exception as e:
            data['error'] = str(e)
        
        return JsonResponse(data, safe=False)

class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'stock/producto/crear.html'
    success_url = reverse_lazy('producto_index')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titlePaginador'] = 'Crear nuevo producto'
        context['infoH4'] = 'Información del producto'
        context['url_listar'] = reverse_lazy('producto_index')
        context['listar'] = 'Listar Productos'
        context['action'] = 'add'
        return context

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'stock/producto/editar.html'
    success_url = reverse_lazy('producto_index')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titlePaginador'] = 'Editar producto'
        context['infoH4'] = 'Información del producto'
        context['url_listar'] = reverse_lazy('producto_index')
        context['listar'] = 'Listar Productos'
        context['action'] = 'edit'
        return context

class ProductDeleteView(DeleteView):
    model = Product
    template_name = './stock/producto/eliminar.html'
    success_url = reverse_lazy('producto_index')

    @method_decorator(login_required)
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titlePaginador'] = 'Eliminar un producto'
        context['infoH4'] = 'Información del producto'
        context['url_listar'] = reverse_lazy('producto_index')
        context['listar'] = 'Listar Productos'
        context['id'] = self.object.id
        return context

def addStockProduct(request, id):
    product = Product.objects.get(id = id)

    if request.method == 'POST':
        stock = request.POST.get("stock")
        if int(request.POST.get("precio")) == 0:
            product.stock += int(stock)
            product.save()
            return redirect('producto_index')
        else:
            precio = request.POST.get("precio")
            product.stock += int(stock)
            product.cost_sale = int(precio)
            product.save()
            return redirect('producto_index')

    return render(request, './stock/producto/agregar_producto.html', context={'product': product})

# CRUD Sale
class SaleListView(ListView):
    model = Sale
    template_name = 'stock/venta/index.html'

    @method_decorator(login_required)
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titlePaginador'] = 'Lista de ventas'
        context['botonCrear'] = 'Crear nueva venta'
        context['urlCrear'] = reverse_lazy('crear_venta')
        context['urlEliminar'] = reverse_lazy('eliminar_venta')
        return context

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Sale.objects.all():
                    data.append(i.toJSON())
            elif action == 'search_details_prod':
                data = []
                for i in Details_sale.objects.filter(invoice_number=request.POST['invoice_number']):
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error.'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)   

class SaleCreateView(CreateView):
    model = Sale
    form_class = SaleForm
    template_name = 'stock/venta/crear.html'
    success_url = reverse_lazy('venta_index')

    @method_decorator(login_required)
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['productos'] = Product.objects.all()
        context['titlePaginador'] = 'Crear nueva venta'
        context['url_listar'] = reverse_lazy('venta_index')
        context['listar'] = 'Listar Ventas'
        context['action'] = 'add'
        return context

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'buscar_productos':
                data = []
                term = request.POST['term']
                prods = Product.objects.filter(~Q(stock__exact=0), Q(name__icontains=term) | Q(brand__icontains=term) | Q(reference__icontains=term))[0:10]
                for i in prods:
                    item = i.toJSON()
                    item['value'] = i.name + ' ' + i.brand + ' ' + i.reference
                    data.append(item)
            elif action == 'add':
                with transaction.atomic():
                    vents = json.loads(request.POST['vents'])
                    sale = Sale()
                    date = datetime.datetime.strptime(vents['date'], '%d/%m/%Y')
                    sale.date = datetime.datetime.strftime(date, '%Y-%m-%d')
                    sale.user = User.objects.get(id = vents['user'])
                    sale.customer = Customer.objects.get(id = vents['customer'])
                    sale.totalSale = int(vents['totalSale'])
                    sale.save()
                    for i in vents['products']:
                        detSale = Details_sale()
                        detSale.invoice_number = Sale.objects.get(invoice_number = sale.invoice_number)
                        detSale.id_product = Product.objects.get(id = i['id'])
                        detSale.quantity = int(i['cant'])
                        product = Product.objects.get(id = detSale.id_product.id)
                        product.stock -= detSale.quantity
                        product.save()
                        detSale.totalPrice = int(i['subtotal'])
                        detSale.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)

project_veristock/stock/templates/stock/venta/eliminar.html
{% extends './../../social/base_eliminar.html' %}

{% block extrajs %}
<script type="text/javascript">

    $('form').on('submit', function (e) {
        e.preventDefault();

        var parameters = $(this).serializeArray();

        $.ajax({
            url: window.location.pathname,
            type: 'POST',
            data: {},
            dataType: 'json'
        }).done(function (data) {
            if(!data.hasOwnProperty('error')) {
                location.href = '{{ url_listar }}';
                return false;
            }
            message_error(data.error);
        }).fail(function (jqXHR, textStatus, errorThrown) {
            alert(textStatus + ': ' + errorThrown);
        }).always(function (data) {
            
        });
    });
</script>
{% endblock extrajs %}

project_veristock/stock/templates/stock/venta/index.html
{% extends "./../../social/listar.html" %}

{% block col %}
<tr>
    <th scope="col" style="width: 10%">#</th>
    <th style="width: 15%">Fecha</th>
    <th style="width: 15%">Cliente</th>
    <th style="width: 15%">Usuario</th>
    <th style="width: 15%">Total Costo</th>
    <th style="width: 5%">Acciones</th>
</tr>
{% endblock col %}

{% block row %}
    
{% endblock row %}

{% block extraContent %}
<div class="modal fade" id="myModalDet" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myLargeModalLabel"><i class="icon-copy fa fa-shopping-cart" aria-hidden="true"></i> Consulta de detalles de productos</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <h5 class="modal-title">{{ product.name }} {{ product.brand }} {{ product.reference }}</h5><br>
                <div class="table-responsive">
                    <table class="table" id="tableDet">
                        <thead>
                            <tr>
                                <th>Producto</th>
                                <th>Precio Unidad</th>
                                <th>Cantidad</th>
                                <th>Subtotal</th>
                            </tr>
                        </thead>
                        
                        <tbody>
                            <tr>
                                
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock extraContent %}

{% block extrajs %}
<script type="text/javascript">

    var tableSale;

    $(function () {

        tableSale = $('#data').DataTable({
            responsive: true,
            autoWidth: false,
            destroy: true,
            deferRender: true,
            ajax: {
                url: window.location.pathname,
                type: 'POST',
                data: {
                    'action': 'searchdata'
                },
                dataSrc: ""
            },
            columns: [
                {"data": "invoice_number"},
                {"data": "date"},
                {"data": "customer.first_name"},
                {"data": "user.first_name"},
                {"data": "totalSale"},
                {"data": 'totalSale'},
            ],
            columnDefs: [
                {
                    targets: [-2],
                    class: 'text-center',
                    orderable: false,
                    render: function (data, type, row) {
                        return '$' + parseInt(data);
                    }
                },
                {
                    targets: [-1],
                    class: 'text-center',
                    orderable: false,
                    render: function (data, type, row) {
                        var buttons = '<a class="dropdown-item" rel="details" data-toggle="tooltip" data-placement="top" title="Consulta de detalles de productos" data-color="#265ed7" style="color: rgb(38, 94, 215);"><i class="icon-copy fa fa-shopping-cart" aria-hidden="true"></i></a>';
                        buttons += '<a class="dropdown-item" data-toggle="tooltip" data-placement="top" title="Editar" href="/venta/editar/' + row.invoice_number + '" data-color="#265ed7" style="color: rgb(38, 94, 215);"><i class="icon-copy dw dw-edit2"></i></a>';
                        buttons += '<a class="dropdown-item" data-toggle="tooltip" data-placement="top" title="Eliminar" href="/venta/eliminar/' + row.invoice_number + '" data-color="#e95959" style="color: rgb(233, 89, 89);"><i class="dw dw-delete-3"></i></a>';
                        return buttons;
                    }
                },
            ],
            language: {
                emptyTable: "No hay registros en la tabla",
                info: "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                infoEmpty: "Mostrando registros del 0 al 0 de un total de 0 registros",
                search: "Buscar: <i class='icon-copy fa fa-search' aria-hidden='true'></i>",
                lengthMenu: "Mostrar _MENU_ registros",
                paginate: {
                    first: "Primero",
                    last: "Último",
                    next: "Siguiente",
                    previous: "Anterior",
                },
            }
        });

        $('#data tbody').on('click', 'a[rel="details"]', function () {
            var tr = tableSale.cell($(this).closest('td, li')).index();
            var data = tableSale.row(tr.row).data();

            console.log(data);
            
            $('#tableDet').DataTable({
                responsive: true,
                autoWidth: false,
                destroy: true,
                deferRender: true,
                ajax: {
                    url: window.location.pathname,
                    type: 'POST',
                    data: {
                        'action': 'search_details_prod',
                        'invoice_number': data.invoice_number
                    },
                    dataSrc: ""
                },
                columns: [
                    {"data": "id_product"},
                    {"data": "id_product.cost_sale"},
                    {"data": "quantity"},
                    {"data": "totalPrice"},
                ],
                columnDefs: [
                    {
                        targets: [0],
                        class: 'text-center',
                        render: function (data, type, row) {
                            return '' + data.name + ' ' + data.brand + ' ' + data.reference + '';
                        }
                    },
                    {
                        targets: [-1],
                        class: 'text-center',
                        render: function (data, type, row) {
                            return '$' + parseInt(data);
                        }
                    },
                    {
                        targets: [-2],
                        class: 'text-center',
                        render: function (data, type, row) {
                            return data;
                        }
                    },
                ],
                initComplete: function (settings, json) {

                },
                language: {
                    emptyTable: "No hay registros en la tabla",
                    info: "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    infoEmpty: "Mostrando registros del 0 al 0 de un total de 0 registros",
                    search: "Buscar: <i class='icon-copy fa fa-search' aria-hidden='true'></i>",
                    lengthMenu: "Mostrar _MENU_ registros",
                    paginate: {
                        first: "Primero",
                        last: "Último",
                        next: "Siguiente",
                        previous: "Anterior",
                    },
                },
            });

            $('#myModalDet').modal('show');
        });        
    });
</script>
{% endblock extrajs %}

project_veristock/stock/templates/stock/venta/invoice.html
<!DOCTYPE html>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<style>
    .img-invoice {
        width: 50px;
        text-align: center;
        margin: 0 auto;
    }

    .head {
        text-align: center;
        text-transform: uppercase;
    }

    #invoice thead tr th {
        text-align: left;
        border-bottom: 1px solid black;
        border-top: 1px solid black;
        padding-top: 4px;
    }

    #invoice thead tr {
        margin-bottom: 0;
        padding-bottom: 0;
    }

    #invoice tbody tr {
        padding: 0;
    }

    .text-center{
        text-align: center;
    }
</style>
<body>
<img src="{{ icon }}" class="img-invoice">
<p class="head">
    {{ comp.name|upper }}<br>
    {{ comp.ruc }}<br>
    {{ comp.address|upper }}
</p>
<p>
    <b>FACTURA:</b> {{ sale.id }}<br>
    <b>FECHA DE VENTA:</b> {{ sale.date_joined }}<br>
    <b>CLIENTE:</b> {{ sale.cli.names|upper }}<br>
    <b>DNI:</b> {{ sale.cli.dni }}<br>
</p>
<table id="invoice">
    <thead>
    <tr>
        <th style="width: 10%;">CANT</th>
        <th style="width: 15%;">P.UNITARIO</th>
        <th style="width: 20%;">CATEGORIA</th>
        <th style="width: 40%;">PRODUCTO</th>
        <th style="width: 15%;">TOTAL</th>
    </tr>
    </thead>
    <tbody>
    {% for d in sale.detsale_set.all %}
        <tr {% if forloop.first %}style="padding-top: 3px;" {% endif %}>
            <td class="text-center">{{ d.cant }}</td>
            <td class="text-center">${{ d.price }}</td>
            <td>{{ d.prod.cat.name }}</td>
            <td>{{ d.prod.name }}</td>
            <td style="text-align: right;">${{ d.subtotal }}</td>
        </tr>
    {% endfor %}
    <tr style="border-top: 1px solid black; padding-top: 4px;">
        <td colspan="4"><b>SUBTOTAL</b></td>
        <td style="text-align: right">{{ sale.subtotal }}</td>
    </tr>
    <tr style="padding-top: 0px;">
        <td colspan="4"><b>IVA 12%</b></td>
        <td style="text-align: right">{{ sale.iva }}</td>
    </tr>
    <tr style="padding-top: 0px;">
        <td colspan="4"><b>TOTAL A PAGAR</b></td>
        <td style="text-align: right">{{ sale.total }}</td>
    </tr>
    </tbody>
</table>
<table style="margin-top: 250px;">
    <thead>
    <tr>
        <th>****GRACIAS POR SU COMPRA****</th>
    </tr>
    <tr>
        <th>NOSE ACEPTAN CAMBIOS NI DEVOLUCIONES</th>
    </tr>
    </thead>
</table>
</body>
</html>

project_veristock/stock/templates/stock/venta/pdf.html
{% load static %}
<!DOCTYPE html>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<style>
    .img-invoice {
        width: 50px;
        text-align: center;
        margin: 0 auto;
    }

    .head {
        text-align: center;
        text-transform: uppercase;
    }

    #invoice thead tr th {
        text-align: left;
        border-bottom: 1px solid black;
        border-top: 1px solid black;
        padding-top: 4px;
    }

    #invoice thead tr {
        margin-bottom: 0;
        padding-bottom: 0;
    }

    #invoice tbody tr {
        padding: 0;
    }

    .text-center{
        text-align: center;
    }
</style>
<body>
<img src="{{ icon }}" class="img-invoice">
<p class="head">
    {{ comp.name|upper }}<br>
    {{ comp.ruc }}<br>
    {{ comp.address|upper }}
</p>
<p>
    <b>FACTURA:</b> {{ sale.invoice_number }}<br>
    <b>FECHA DE VENTA:</b> {{ sale.date }}<br>
    <b>CLIENTE:</b> {{ sale.customer.first_name|upper }} {{ sale.customer.last_names|upper }}<br>
    <b>DOCUMENTO:</b> {{ sale.customer.type_document }} {{ sale.customer.document_number }}<br> 
</p>
<table id="invoice">
    <thead>
    <tr>
        <th style="width: 20%;">CANTIDAD</th>
        <th style="width: 40%;">PRECIO UNITARIO</th>
        <th style="width: 40%;">PRODUCTO</th>
        <th style="width: 20%;">SUBTOTAL</th>
    </tr>
    </thead>
    <tbody>
    {% for d in sale.details_sale_set.all %}
        <tr {% if forloop.first %}style="padding-top: 3px;" {% endif %}>
            <td>{{ d.quantity }}</td>
            <td>${{ d.id_product.cost_sale }}</td>
            <td>{{ d.id_product }}</td>
            <td>${{ d.totalPrice }}</td>
        </tr>
    {% endfor %}
    <tr style="padding-top: 0px;">
        <td colspan="4"><b>TOTAL A PAGAR</b></td>
        <td style="text-align: right">{{ sale.total }}</td>
    </tr>
    </tbody>
</table>
<table style="margin-top: 250px;">
    <thead>
    <tr>
        <th>****GRACIAS POR SU COMPRA****</th>
    </tr>
    <tr>
        <th>NO SE ACEPTAN CAMBIOS NI DEVOLUCIONES</th>
    </tr>
    </thead>
</table>
</body>
</html>